name: asl_fingerspelling
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - tensorflow
  - matplotlib
  - ipywidgets
  - pip
  - pip:
    - opencv-python
    - mediapipe
    - jupyter
    - ipykernel
    - pyarrow
    - scikit-image
    - scikit-learn
variables:
  SIS_DATASET_INPUT_PATH: "/media/nas/Datasets/asl_fingerspelling"
  SIS_DATASET_PREPROC_PATH: "/media/nas/Datasets/asl_fingerspelling_tfrec"
